sonar.projectKey=JITNONGNOOONG1
sonar.projectName=JITNONGNOOONG1
sonar.host.url=https://ominous-space-xylophone-x5pvwqrw4vx4f6pr4-9000.app.github.dev
sonar.sources=implementations/src
sonar.tests=implementations/tests
sonar.javascript.lcov.reportPaths=implementations/coverage/lcov.info
sonar.coverage.exclusions=**/frontend/**,**/server.js,**/config/**,**/scripts/**
sonar.exclusions=**/node_modules/**,**/coverage/**
sonar.javascript.node.maxspace=4096