sonar.projectKey=JITNONGNOOONG1
sonar.projectName=JITNONGNOOONG1
sonar.organization=maomidmao

sonar.sources=implementations/src
sonar.tests=implementations/tests
sonar.javascript.lcov.reportPaths=implementations/coverage/lcov.info
sonar.coverage.exclusions=**/frontend/**,**/server.js,**/config/**,**/scripts/**
sonar.exclusions=**/node_modules/**,**/coverage/**
sonar.javascript.node.maxspace=4096