name: CI Pipeline

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:

jobs:
  build:
    name: Build + Test + Sonar
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: implementations

      - name: Run tests
        run: npm test || echo "No tests"
        working-directory: implementations

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
